;;;; emit.lisp — writing the generated Lisp sources

(in-package #:gtk4.generator)

(defparameter *m1-targets*
  '(("GLib" "2.0") ("GObject" "2.0") ("GModule" "2.0") ("Gio" "2.0"))
  "Namespaces generated in milestone M1.")

;;; Documentation

(defparameter *doc-bases*
  '(("GLib" . "https://docs.gtk.org/glib/") ("GObject" . "https://docs.gtk.org/gobject/")
    ("GModule" . "https://docs.gtk.org/gmodule/") ("Gio" . "https://docs.gtk.org/gio/")
    ("Pango" . "https://docs.gtk.org/Pango/") ("PangoCairo" . "https://docs.gtk.org/PangoCairo/")
    ("GdkPixbuf" . "https://docs.gtk.org/gdk-pixbuf/") ("Gdk" . "https://docs.gtk.org/gdk4/")
    ("Gsk" . "https://docs.gtk.org/gsk4/") ("Gtk" . "https://docs.gtk.org/gtk4/")
    ("Adw" . "https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/"))
  "Where each namespace's gi-docgen reference lives.")

(defun doc-url (nsname fragment)
  (let ((base (cdr (assoc nsname *doc-bases* :test #'string=))))
    (and base fragment (concatenate 'string base fragment))))

(defun clean-doc (text)
  "The first paragraph of a GIR doc string, rewritten with Lisp names."
  (convert-doc-text (first-paragraph text)))

(defun docstring (doc &key c-name url version deprecated)
  (join-paragraphs (list (clean-doc doc) (reference-lines c-name url version deprecated))))

(defun callable-fragment (plan)
  (let ((owner (plan-owner plan))
        (name (gir-item-name (plan-source plan))))
    (if owner
        (format nil "~a.~a.~a.html"
                (ecase (plan-kind plan)
                  (:method "method") (:constructor "ctor") (:function "type_func"))
                (gir-item-name owner) name)
        (format nil "func.~a.html" name))))

(defun type-fragment (item)
  (format nil "~a.~a.html"
          (etypecase item
            (gir-enum (if (eq (gir-enum-kind item) :bitfield) "flags" "enum"))
            (gir-class (ecase (gir-class-kind item)
                         (:class "class") (:interface "iface")
                         ((:record :boxed) "struct") (:union "union"))))
          (gir-item-name item)))

;;; Printing

(defun write-form (form stream)
  (let ((*print-case* :downcase)
        (*print-pretty* t)
        (*print-right-margin* 100)
        (*print-readably* nil)
        (*print-circle* nil))
    (terpri stream)
    (pprint form stream)
    (terpri stream)))

(defun write-header (stream source)
  (format stream ";;;; Generated by gtk4-generator from ~a.~%;;;; Do not edit: change the generator or its overrides and regenerate.~%"
          (file-namestring source)))

;;; Constants

(defun constant-value (c)
  (let ((v (gir-constant-value c))
        (type (and (gir-type-p (gir-constant-type c)) (gir-type-name (gir-constant-type c)))))
    (cond ((null v) nil)
          ((member type '("gint" "guint" "gint8" "guint8" "gint16" "guint16" "gint32" "guint32"
                          "gint64" "guint64" "glong" "gulong" "gsize" "gssize" "gshort" "gushort")
                   :test #'equal)
           (or (parse-integer v :junk-allowed t) v))
          ((member type '("gdouble" "gfloat") :test #'equal)
           (let ((*read-default-float-format* 'double-float))
             (handler-case (coerce (read-from-string v) 'double-float)
               (error () v))))
          ((equal type "gboolean") (and (string-equal v "true") t))
          (t v))))

;;; Class ordering and superclasses

(defun interface-ancestors (ctx qualified &optional (seen (make-hash-table :test 'equal)))
  "All interfaces QUALIFIED (an interface) requires, transitively."
  (let ((item (lookup ctx qualified)))
    (when (gir-class-p item)
      (loop for p in (gir-class-prerequisites item)
            for q = (qualify p (namespace-of qualified))
            for pi* = (lookup ctx q)
            when (and (gir-class-p pi*) (eq (gir-class-kind pi*) :interface)
                      (not (gethash q seen)))
              do (setf (gethash q seen) t)
                 (interface-ancestors ctx q seen)))
    (alexandria:hash-table-keys seen)))

(defun class-implemented (ctx qualified)
  "Every interface QUALIFIED (a class) implements, including through ancestors."
  (let ((result '()))
    (loop for name = qualified then (let ((p (gir-class-parent item)))
                                      (and p (qualify p (namespace-of name))))
          for item = (and name (lookup ctx name))
          while (gir-class-p item)
          do (dolist (i (gir-class-implements item))
               (let ((q (qualify i (namespace-of name))))
                 (pushnew q result :test #'string=)
                 (dolist (a (interface-ancestors ctx q)) (pushnew a result :test #'string=)))))
    result))

(defun minimal-interfaces (ctx candidates exclude)
  "CANDIDATES (qualified interface names) without those in EXCLUDE and without
any required by another candidate, so class precedence lists stay consistent."
  (let ((cands (remove-if (lambda (q) (or (member q exclude :test #'string=)
                                          (not (type-symbol q))
                                          (not (gir-class-p (lookup ctx q)))
                                          (not (eq (gir-class-kind (lookup ctx q)) :interface))))
                          (remove-duplicates candidates :test #'string=))))
    (remove-if (lambda (q)
                 (some (lambda (other)
                         (and (not (string= q other))
                              (member q (interface-ancestors ctx other) :test #'string=)))
                       cands))
               cands)))

(defun superclasses (ctx item nsname)
  (let ((qualified (qualify (gir-item-name item) nsname)))
    (ecase (gir-class-kind item)
      (:interface
       (mapcar #'type-symbol
               (minimal-interfaces ctx
                                   (mapcar (lambda (p) (qualify p nsname)) (gir-class-prerequisites item))
                                   '())))
      (:class
       (let* ((parent (and (gir-class-parent item) (qualify (gir-class-parent item) nsname)))
              (parent-sym (or (and parent (gobject-type-p ctx parent) (type-symbol parent))
                              (find-symbol "OBJECT" "GTK4.RUNTIME")))
              (inherited (and parent (class-implemented ctx parent)))
              (own (mapcar (lambda (i) (qualify i nsname)) (gir-class-implements item))))
         (declare (ignore qualified))
         (cons parent-sym (mapcar #'type-symbol (minimal-interfaces ctx own inherited))))))))

(defun ordered-classes (ctx ns)
  "Classes and interfaces of NS that descend from GObject, each after any
same-namespace class or interface it inherits from."
  (let* ((nsname (gir-namespace-name ns))
         (wanted (remove-if-not (lambda (c)
                                  (and (member (gir-class-kind c) '(:class :interface))
                                       (gobject-type-p ctx (qualify (gir-item-name c) nsname))
                                       (not (assoc (qualify (gir-item-name c) nsname)
                                                   *runtime-types* :test #'string=))))
                                (gir-namespace-classes ns)))
         (order '())
         (seen (make-hash-table :test 'eq)))
    (labels ((visit (c)
               (unless (gethash c seen)
                 (setf (gethash c seen) t)
                 (dolist (dep (append (and (gir-class-parent c) (list (gir-class-parent c)))
                                      (gir-class-implements c)
                                      (gir-class-prerequisites c)))
                   (let ((d (lookup ctx (qualify dep nsname))))
                     (when (member d wanted) (visit d))))
                 (push c order))))
      (mapc #'visit wanted))
    (nreverse order)))

;;; Function forms

(defun plan-form (plan nsname)
  `(gtk4.runtime:define-gfunction (,(plan-symbol plan) ,(plan-c-name plan))
     ,@(when (plan-args plan)
         `(:args ,(loop for (var spec . options) in (plan-args plan)
                        collect `(,var ,spec
                                  ,@(when (getf options :user-data-of)
                                      `(:user-data-of ,(getf options :user-data-of)))
                                  ,@(when (getf options :destroy-of)
                                      `(:destroy-of ,(getf options :destroy-of)))
                                  ,@(when (getf options :length-of)
                                      `(:length-of ,(getf options :length-of)))
                                  ,@(when (eq (getf options :direction) :out) '(:direction :out))
                                  ,@(when (getf options :caller-allocates) '(:caller-allocates t))
                                  ,@(unless (member (getf options :transfer) '(nil :none))
                                      `(:transfer ,(getf options :transfer)))
                                  ,@(when (getf options :optional) '(:optional t))))))
     ,@(unless (eq (plan-return plan) :void) `(:return ,(plan-return plan)))
     ,@(unless (eq (plan-return-transfer plan) :none)
         `(:return-transfer ,(plan-return-transfer plan)))
     ,@(when (plan-throws plan) '(:throws t))
     ,@(when (plan-version plan) `(:version ,(plan-version plan)))
     ,@(let ((url (plan-url plan nsname))) (when url `(:url ,url)))
     :documentation ,(plan-docstring plan nsname (plan-url plan nsname))))

(defun plan-url (plan nsname)
  (or (gethash (plan-source plan) *override-urls*)
      (doc-url nsname (callable-fragment plan))))

(defun namespace-callables (ns)
  "(CALLABLE . OWNER) for every function, constructor and method in NS."
  (append (mapcar (lambda (f) (cons f nil)) (gir-namespace-functions ns))
          (loop for c in (gir-namespace-classes ns)
                append (loop for f in (append (gir-class-constructors c)
                                              (gir-class-functions c)
                                              (gir-class-methods c))
                             collect (cons f c)))
          (loop for e in (gir-namespace-enums ns)
                append (mapcar (lambda (f) (cons f e)) (gir-enum-functions e)))))

;;; Async functions and their _finish functions

(defun async-callback-position (plan)
  "Where PLAN's GAsyncReadyCallback goes among its visible arguments, or NIL."
  (let ((visible (remove-if (lambda (a)
                              (or (eq (getf (cddr a) :direction) :out)
                                  (getf (cddr a) :user-data-of) (getf (cddr a) :destroy-of)
                                  (getf (cddr a) :length-of)))
                            (plan-args plan))))
    (position-if (lambda (a)
                   (let ((spec (second a)))
                     (and (consp spec) (eq (first spec) :callback)
                          (eq (second spec) (type-symbol "Gio.AsyncReadyCallback")))))
                 visible)))

(defun async-pairs (plans)
  "A DEFINE-ASYNC form for each plan taking a GAsyncReadyCallback whose
_finish function is bound too: the one GIR names, else the name with _async
replaced by (or followed by) _finish."
  (let ((by-c-name (make-hash-table :test 'equal)))
    (dolist (p plans) (setf (gethash (plan-c-name p) by-c-name) p))
    (loop for p in plans
          for position = (async-callback-position p)
          for c-name = (plan-c-name p)
          for finish = (and position
                            (let ((ff (gir-callable-finish-func (plan-source p))))
                              ;; GIR gives the finish function's name without
                              ;; the C prefix the async function's name carries.
                              (or (and ff (or (gethash (concatenate
                                                        'string
                                                        (subseq c-name 0 (- (length c-name)
                                                                            (length (gir-item-name (plan-source p)))))
                                                        ff)
                                                       by-c-name)
                                              (gethash ff by-c-name)))
                                  (let ((n (length c-name)))
                                    (and (> n 6) (string= "_async" (subseq c-name (- n 6)))
                                         (gethash (concatenate 'string (subseq c-name 0 (- n 6)) "_finish")
                                                  by-c-name)))
                                  (gethash (concatenate 'string c-name "_finish") by-c-name))))
          when finish
            collect `(gtk4.runtime:define-async ,(plan-symbol p) ,(plan-symbol finish)
                       :callback-position ,position
                       :finish-takes-source ,(and (eq (plan-kind finish) :method) t)))))

;;; Writing one namespace

(defparameter *functions-per-file* 400
  "Generated functions per file. Splitting large namespaces bounds the memory
SBCL needs to compile each file (GTK alone has over 3,700 functions).")

(defun emit-namespace (ctx ns stream &key function-stream-maker)
  "Write NS's types, layouts and properties to STREAM. Functions go to the
streams FUNCTION-STREAM-MAKER returns, called with the chunk index and a
function that writes the chunk."
  (let* ((nsname (gir-namespace-name ns))
         (*package* (find-package (namespace-package-name nsname))))
    (write-header stream (gir-namespace-source ns))
    (format stream "~%(in-package #:~(~a~))~%" (package-name *package*))
    (let ((library (cdr (assoc nsname *namespace-libraries* :test #'string=))))
      (when library
        (format stream "~%;;; Not one of the libraries the runtime loads by default.~%")
        (write-form `(eval-when (:compile-toplevel :load-toplevel :execute)
                       (gtk4.runtime:load-libraries
                        :libraries '(,(intern library "GTK4.RUNTIME"))))
                    stream)))
    ;; Enums and flags
    (format stream "~%;;; Enums and flags~%")
    (dolist (e (gir-namespace-enums ns))
      (write-form
       `(gtk4.runtime:define-genum ,(type-symbol (qualify (gir-item-name e) nsname))
            (:kind ,(if (eq (gir-enum-kind e) :bitfield) :flags :enum)
             ,@(when (gir-enum-get-type e)
                 `(:gtype-name ,(gir-enum-glib-type-name e) :get-type ,(gir-enum-get-type e)))
             :c-name ,(gir-enum-c-type e)
             ,@(let ((url (doc-url nsname (type-fragment e)))) (when url `(:url ,url)))
             :documentation ,(docstring (gir-item-doc e) :c-name (gir-enum-c-type e)
                                                         :url (doc-url nsname (type-fragment e))))
          ,@(loop for m in (gir-enum-members e)
                  collect (cons (intern (string-upcase (snake-to-kebab (gir-member-name m))) :keyword)
                                (gir-member-value m))))
       stream))
    ;; GError domains
    (format stream "~%;;; Error domains~%")
    (dolist (e (gir-namespace-enums ns))
      (let ((conditions (gethash e *error-conditions*)))
        (when conditions
          (write-form
           `(gtk4.runtime:define-gerror-domain ,(first conditions)
                (,(gir-enum-error-domain e) ,(type-symbol (qualify (gir-item-name e) nsname)))
              ,@(rest conditions))
           stream))))
    ;; Constants
    (format stream "~%;;; Constants~%")
    (dolist (c (gir-namespace-constants ns))
      (let ((sym (item-symbol c)))
        (when sym
          (write-form `(gtk4.runtime:define-gconstant ,sym ,(constant-value c)
                         ,(docstring (gir-item-doc c) :c-name (gir-constant-c-type c)
                                                      :url (doc-url nsname (format nil "const.~a.html"
                                                                                   (gir-item-name c)))))
                      stream))))
    ;; Classes and interfaces
    (format stream "~%;;; Classes and interfaces~%")
    (dolist (c (ordered-classes ctx ns))
      (write-form
       `(gtk4.runtime:define-gclass ,(type-symbol (qualify (gir-item-name c) nsname))
            ,(superclasses ctx c nsname)
          (:gtype-name ,(gir-class-glib-type-name c)
           :get-type ,(gir-class-get-type c)
           :c-name ,(gir-class-c-type c)
           ,@(let ((url (doc-url nsname (type-fragment c)))) (when url `(:url ,url)))
           :documentation ,(docstring (gir-item-doc c) :c-name (gir-class-c-type c)
                                                       :url (doc-url nsname (type-fragment c)))))
       stream))
    ;; Boxed records
    (format stream "~%;;; Boxed types~%")
    (dolist (c (gir-namespace-classes ns))
      (let ((q (qualify (gir-item-name c) nsname)))
        (when (and (member (gir-class-kind c) '(:record :union :boxed))
                   (gir-class-get-type c)
                   (not (gir-class-is-gtype-struct-for c))
                   (not (member q *pointer-records* :test #'string=)))
          (write-form
           `(gtk4.runtime:define-grecord ,(type-symbol q)
                (:gtype-name ,(gir-class-glib-type-name c)
                 :c-name ,(gir-class-c-type c)
                 ,@(let ((url (doc-url nsname (type-fragment c)))) (when url `(:url ,url)))
                 :documentation ,(docstring (gir-item-doc c) :c-name (gir-class-c-type c)
                                                             :url (doc-url nsname (type-fragment c)))))
           stream))))
    ;; Struct layouts, field accessors, constructors
    (format stream "~%;;; Struct layouts~%")
    (dolist (l (namespace-layouts-in-order ctx ns))
      (write-form
       `(gtk4.runtime:define-gstruct ,(layout-symbol l)
            (,@(when (layout-union l) '(:union t))
             ,@(when (layout-gtype-name l) `(:gtype-name ,(layout-gtype-name l))))
          ,@(layout-fields l))
       stream)
      (let ((struct-spec (if (layout-gtype-name l)
                             (list :boxed (layout-gtype-name l)
                                   (gir-class-get-type (layout-item l)) (layout-symbol l))
                             (list :record (layout-symbol l)))))
        (dolist (a (remove nil (layout-accessors l) :key (lambda (a) (getf a :name))))
          (write-form
           `(gtk4.runtime:define-gfield ,(getf a :name) ,(layout-symbol l) ,(getf a :slot) ,(getf a :spec)
              ,@(when (getf a :writable) '(:writable t))
              ,@(when (getf a :bits) `(:bits ,(getf a :bits)))
              ,@(when (getf a :inline) '(:inline t))
              :documentation ,(docstring (gir-item-doc (getf a :field))
                                         :url (and (layout-qualified l)
                                                   (doc-url nsname (type-fragment (layout-item l))))))
           stream))
        (when (layout-constructor l)
          (write-form
           `(gtk4.runtime:define-gstruct-constructor ,(layout-constructor l) ,struct-spec
              ,(loop for a in (layout-accessors l)
                     when (and (getf a :writable) (getf a :name))
                       collect `(,(intern (string-upcase (safe-variable-name (gir-item-name (getf a :field))))
                                          (symbol-package (layout-symbol l)))
                                 ,(getf a :slot) ,(getf a :spec)
                                 ,@(when (getf a :bits) `(:bits ,(getf a :bits)))
                                 ,@(when (getf a :inline) '(:inline t))))
              :documentation ,(format nil "A new ~a with the given fields; others are zero."
                                      (gir-item-name (layout-item l))))
           stream))))
    ;; Properties
    (format stream "~%;;; Properties~%")
    (dolist (c (ordered-classes ctx ns))
      (dolist (p (gir-class-properties c))
        (let ((sym (item-symbol p)))
          (when sym
            (write-form
             `(gtk4.runtime:define-gproperty ,sym ,(gir-item-name p)
                  (:readable ,(gir-property-readable p)
                   :writable ,(and (gir-property-writable p) (not (gir-property-construct-only p)))
                   :documentation ,(docstring (gir-item-doc p)
                                              :url (doc-url nsname (format nil "property.~a.~a.html"
                                                                           (gir-item-name c)
                                                                           (gir-item-name p))))))
             stream)))))
    ;; Callback types
    (format stream "~%;;; Callback types~%")
    (dolist (cb (gir-namespace-callbacks ns))
      (let* ((qualified (qualify (gir-item-name cb) nsname))
             (plan (callback-plan ctx qualified)))
        (unless (stringp plan)
          (destructuring-bind (args ret transfer) plan
            (write-form
             `(gtk4.runtime:define-gcallback ,(type-symbol qualified)
                  (:args ,(loop for (var spec . options) in args
                                collect `(,var ,spec
                                          ,@(when (getf options :user-data) '(:user-data t))
                                          ,@(unless (member (getf options :transfer) '(nil :none))
                                              `(:transfer ,(getf options :transfer)))))
                   ,@(unless (eq ret :void) `(:return ,ret))
                   ,@(unless (eq transfer :none) `(:return-transfer ,transfer))))
             stream)))))
    ;; Functions, in chunks
    (let ((plans '()))
      (loop for (callable . owner) in (namespace-callables ns)
            do (multiple-value-bind (plan reason) (plan-callable ctx ns callable owner)
                 (if plan
                     (progn (setf (gethash callable *plans*) plan)
                            (push plan plans))
                     (note-skip ctx ns (or (gir-callable-c-identifier callable)
                                           (gir-item-name callable))
                                reason))))
      (setf plans (nreverse plans))
      (setf (gethash nsname (context-bound ctx)) (length plans))
      ;; Async functions paired with their _finish functions, for gio:async.
      (setf plans (append plans (async-pairs plans)))
      ;; Virtual functions follow the functions, in the same chunks.
      (let ((vplans '()))
        (loop for (vfunc . owner) in (namespace-vfuncs ctx ns)
              do (multiple-value-bind (vp reason) (plan-vfunc ctx ns vfunc owner)
                   (setf (gethash vfunc *vfunc-plans*) (or vp reason))
                   (if vp
                       (push vp vplans)
                       (push (cons (format nil "~a.~a" (gir-item-name owner) (gir-item-name vfunc))
                                   reason)
                             (gethash nsname (context-vfuncs-skipped ctx))))))
        (setf (gethash nsname (context-vfuncs-bound ctx)) (length vplans))
        (setf plans (append plans (nreverse vplans))))
      (loop for chunk from 1
            while plans
            do (let ((these (subseq plans 0 (min *functions-per-file* (length plans)))))
                 (setf plans (nthcdr (length these) plans))
                 (funcall function-stream-maker chunk
                          (lambda (out)
                            (let ((*package* (find-package (namespace-package-name nsname))))
                              (write-header out (gir-namespace-source ns))
                              (format out "~%(in-package #:~(~a~))~%" (package-name *package*))
                              (format out "~%;;; Functions, constructors, methods and virtual functions (part ~d)~%" chunk)
                              (dolist (plan these)
                                (write-form (cond ((vfunc-plan-p plan) (vfunc-form plan nsname))
                                                  ((plan-p plan) (plan-form plan nsname))
                                                  (t plan))
                                            out)))))))
      ns)))

(defun namespace-file-base (ns)
  (string-downcase (namespace-package-name (gir-namespace-name ns))))

(defun write-namespace-files (ctx ns directory)
  "Write NS's generated files into DIRECTORY; return their names, in load order."
  (let* ((base (namespace-file-base ns))
         (files (list base)))
    (with-open-file (out (merge-pathnames (format nil "~a.lisp" base) directory)
                         :direction :output :if-exists :supersede)
      (emit-namespace ctx ns out
                      :function-stream-maker
                      (lambda (chunk writer)
                        (let ((name (format nil "~a-functions-~d" base chunk)))
                          (push name files)
                          (with-open-file (fout (merge-pathnames (format nil "~a.lisp" name) directory)
                                                :direction :output :if-exists :supersede)
                            (funcall writer fout))))))
    (nreverse files)))

;;; ASDF systems for the generated files, written between markers in gtk4.asd

(defparameter *asd-begin* ";;; BEGIN GENERATED SYSTEMS (written by gtk4-generator; do not edit)")
(defparameter *asd-end* ";;; END GENERATED SYSTEMS")

(defun system-name (ns)
  (format nil "gtk4/~a" (namespace-file-base ns)))

(defun generated-systems-text (ctx files-by-namespace)
  (with-output-to-string (out)
    (format out "~a~%~%(defsystem \"gtk4/packages\"~%  :depends-on (\"gtk4/runtime\")~%  :pathname \"src/generated/\"~%  :components ((:file \"packages\")))~%"
            *asd-begin*)
    (dolist (ns (context-targets ctx))
      (let ((deps (or (loop for (iname iversion) in (gir-namespace-includes ns)
                            for dep = (find-if (lambda (n) (and (string= (gir-namespace-name n) iname)
                                                                (string= (gir-namespace-version n) iversion)))
                                               (context-targets ctx))
                            when dep collect (system-name dep))
                      (list "gtk4/packages"))))
        (format out "~%(defsystem ~s~%  :depends-on (~{~s~^ ~})~%  :pathname \"src/generated/\"~%  :serial t~%  :components (~{(:file ~s)~^~%               ~}))~%"
                (system-name ns) deps (cdr (assoc ns files-by-namespace)))))
    (format out "~%~a~%" *asd-end*)))

(defun update-asd (ctx files-by-namespace)
  "Replace the generated-systems region of gtk4.asd."
  (let* ((path (asdf:system-relative-pathname "gtk4-generator" "gtk4.asd"))
         (text (uiop:read-file-string path))
         (start (search *asd-begin* text))
         (end (search *asd-end* text)))
    (unless (and start end)
      (error "gtk4.asd has no generated-systems markers"))
    (with-open-file (out path :direction :output :if-exists :supersede)
      (write-string (subseq text 0 start) out)
      (write-string (string-right-trim '(#\Newline) (generated-systems-text ctx files-by-namespace)) out)
      (write-string (subseq text (+ end (length *asd-end*))) out))))

;;; The packages file

(defun emit-packages (ctx stream)
  (format stream ";;;; Generated by gtk4-generator. Do not edit.~%")
  (format stream ";;;; One package per GIR namespace; every binding symbol is exported.~%")
  (dolist (ns (context-targets ctx))
    (let* ((package (find-package (namespace-package-name (gir-namespace-name ns))))
           (runtime (find-package "GTK4.RUNTIME"))
           (externals (sort (loop for s being the external-symbols of package collect s)
                            #'string< :key #'symbol-name))
           (imported (remove-if-not (lambda (s) (eq (symbol-package s) runtime)) externals))
           (shadows (sort (mapcar #'symbol-name (package-shadowing-symbols package)) #'string<)))
      (format stream "~%(defpackage #:~(~a~)~%  (:use #:cl)~%  (:local-nicknames (#:rt #:gtk4.runtime))"
              (package-name package))
      (when shadows
        (format stream "~%  (:shadow~{ #:~(~a~)~})" shadows))
      (when imported
        (format stream "~%  (:import-from #:gtk4.runtime~{ #:~(~a~)~})" (mapcar #'symbol-name imported)))
      (format stream "~%  (:export~{~%   #:~(~a~)~}))~%" (mapcar #'symbol-name externals)))))

;;; Coverage

(defun callable-total (ns)
  (length (namespace-callables ns)))

(defparameter *never-bindable*
  '("not introspectable" "moved elsewhere (alias)" "shadowed by another function"
    "GLib container API (containers are Lisp values)")
  "Skip reasons that mean a callable should not be bound: GIR says so, or the
Lisp API replaces it by design.")

(defun emit-coverage (ctx stream)
  (format stream "# Binding coverage~%~%Generated by gtk4-generator. Callables are functions, constructors and methods. ")
  (format stream "Bindable excludes those GIR marks as not introspectable, aliases, shadowed functions, and GLib's own container API (GList, GHashTable and friends are plain Lisp values here).~%~%")
  (format stream "| Namespace | Callables | Bindable | Bound | Coverage of bindable |~%| --- | ---: | ---: | ---: | ---: |~%")
  (let ((total 0) (bindable-total 0) (bound 0))
    (dolist (ns (context-targets ctx))
      (let* ((name (gir-namespace-name ns))
             (n (callable-total ns))
             (never (count-if (lambda (skip) (member (cdr skip) *never-bindable* :test #'string=))
                              (gethash name (context-skipped ctx))))
             (bindable (- n never))
             (b (gethash name (context-bound ctx) 0)))
        (incf total n) (incf bindable-total bindable) (incf bound b)
        (format stream "| ~a | ~d | ~d | ~d | ~,1f% |~%" name n bindable b
                (if (zerop bindable) 100 (* 100.0 (/ b bindable))))))
    (format stream "| **Total** | ~d | ~d | ~d | ~,1f% |~%" total bindable-total bound
            (if (zerop bindable-total) 100 (* 100.0 (/ bound bindable-total)))))
  (format stream "~%## Virtual functions~%~%Virtual functions a Lisp subclass can override with `gobject:define-vfunc`.~%~%| Namespace | Virtual functions | Overridable |~%| --- | ---: | ---: |~%")
  (let ((total 0) (bound 0))
    (dolist (ns (context-targets ctx))
      (let* ((name (gir-namespace-name ns))
             (b (gethash name (context-vfuncs-bound ctx) 0))
             (n (+ b (length (gethash name (context-vfuncs-skipped ctx))))))
        (incf total n) (incf bound b)
        (format stream "| ~a | ~d | ~d |~%" name n b)))
    (format stream "| **Total** | ~d | ~d |~%" total bound))
  (format stream "~%| Why a virtual function is not overridable | Count |~%| --- | ---: |~%")
  (let ((reasons (make-hash-table :test 'equal)))
    (loop for skips being the hash-values of (context-vfuncs-skipped ctx)
          do (loop for (nil . reason) in skips
                   do (incf (gethash (reason-category reason) reasons 0))))
    (loop for (reason . count) in (sort (alexandria:hash-table-alist reasons) #'> :key #'cdr)
          do (format stream "| ~a | ~d |~%" reason count)))
  (format stream "~%## Why callables are skipped~%~%| Reason | Count |~%| --- | ---: |~%")
  (let ((reasons (make-hash-table :test 'equal)))
    (loop for skips being the hash-values of (context-skipped ctx)
          do (loop for (nil . reason) in skips
                   do (incf (gethash (reason-category reason) reasons 0))))
    (loop for (reason . count) in (sort (alexandria:hash-table-alist reasons) #'> :key #'cdr)
          do (format stream "| ~a | ~d |~%" reason count))))

(defun emit-gap-lists (ctx stream)
  "Every bindable callable that is not bound and every virtual function that
cannot be overridden, each with its reason."
  (format stream "~%## Every gap~%~%Callables that are bindable but not bound, by namespace. Most need an override (a GIR annotation is missing or wrong) or a marshalling feature the runtime lacks; the reason says which.~%")
  (dolist (ns (context-targets ctx))
    (let ((gaps (sort (remove-if (lambda (skip) (member (cdr skip) *never-bindable* :test #'string=))
                                 (copy-list (gethash (gir-namespace-name ns) (context-skipped ctx))))
                      #'string< :key #'car)))
      (when gaps
        (format stream "~%### ~a (~d)~%~%| Callable | Reason |~%| --- | --- |~%"
                (gir-namespace-name ns) (length gaps))
        (loop for (what . why) in gaps
              do (format stream "| `~a` | ~a |~%" what why)))))
  (format stream "~%## Virtual functions that cannot be overridden~%")
  (dolist (ns (context-targets ctx))
    (let ((gaps (sort (copy-list (gethash (gir-namespace-name ns) (context-vfuncs-skipped ctx)))
                      #'string< :key #'car)))
      (when gaps
        (format stream "~%### ~a (~d)~%~%| Virtual function | Reason |~%| --- | --- |~%"
                (gir-namespace-name ns) (length gaps))
        (loop for (what . why) in gaps
              do (format stream "| `~a` | ~a |~%" what why))))))

(defun reason-category (reason)
  "Group reasons that differ only in a type name."
  (let ((p (search "unresolved type" reason)))
    (if p (subseq reason 0 (+ p (length "unresolved type"))) reason)))

;;; Entry point

(defun generate (&key (targets *target-namespaces*)
                      (output-directory (asdf:system-relative-pathname "gtk4" "src/generated/"))
                      site-directory)
  "Generate binding sources for TARGETS into OUTPUT-DIRECTORY: packages.lisp,
one file per namespace, and COVERAGE.md. Run in a fresh image."
  (let* ((repository (load-targets :targets targets))
         (ctx (make-context repository targets)))
    (name-namespaces ctx)
    (build-doc-index ctx)
    (ensure-directories-exist output-directory)
    ;; Remove files from earlier runs, which may have had more chunks.
    (dolist (old (directory (merge-pathnames "*.lisp" output-directory)))
      (delete-file old))
    (let ((files (loop for ns in (context-targets ctx)
                       collect (cons ns (write-namespace-files ctx ns output-directory)))))
      (update-asd ctx files))
    (with-open-file (out (merge-pathnames "packages.lisp" output-directory)
                         :direction :output :if-exists :supersede)
      (emit-packages ctx out))
    (with-open-file (out (merge-pathnames "COVERAGE.md" output-directory)
                         :direction :output :if-exists :supersede)
      (emit-coverage ctx out))
    (with-open-file (out (merge-pathnames "COVERAGE.md" output-directory)
                         :direction :output :if-exists :append)
      (emit-gap-lists ctx out))
    (emit-coverage ctx *standard-output*)
    (when site-directory
      (generate-site ctx site-directory)
      (format t "~&Reference site written to ~a~%" site-directory))
    ctx))
