;;;; overrides/cairo.lisp — cairo's functions, which its GIR file leaves out
;;;;
;;;; cairo-1.0.gir describes cairo's types (as GObject boxed types, via
;;;; cairo-gobject) and enums, but only one function. This spec adds the
;;;; drawing API from cairo.h. Function names drop the cairo_ prefix:
;;;; cairo_move_to is cairo:move-to. Documentation links point into the
;;;; cairo manual, https://www.cairographics.org/manual/.

(in-package #:gtk4.generator)

(defparameter *cairo-manual* "https://www.cairographics.org/manual/")

(defun cairo-page (page) (concatenate 'string *cairo-manual* page))

(define-override "cairo" (ns)
  ;; GIR's one function is a placeholder without parameters; replace it.
  (remove-functions ns "image_surface_create")
  ;; Struct layouts GIR omits.
  (set-record-fields ns "Matrix"
                     '(("xx" "gdouble") ("yx" "gdouble") ("xy" "gdouble")
                       ("yy" "gdouble") ("x0" "gdouble") ("y0" "gdouble")))
  (add-record ns "TextExtents" "cairo_text_extents_t"
              '(("x_bearing" "gdouble") ("y_bearing" "gdouble") ("width" "gdouble")
                ("height" "gdouble") ("x_advance" "gdouble") ("y_advance" "gdouble"))
              "The extents of a piece of text, in user-space units.")
  (add-record ns "FontExtents" "cairo_font_extents_t"
              '(("ascent" "gdouble") ("descent" "gdouble") ("height" "gdouble")
                ("max_x_advance" "gdouble") ("max_y_advance" "gdouble"))
              "The extents of a font, in user-space units.")

  (add-functions
   ns "cairo_" (cairo-page "cairo-cairo-t.html")
   '(("create" ("Context" :transfer :full) (("target" "Surface"))
      "A new drawing context targeting TARGET.")
     ("status" "Status" (("cr" "Context")) "The current error status of CR.")
     ("save" "none" (("cr" "Context")) "Push a copy of CR's state onto its state stack.")
     ("restore" "none" (("cr" "Context")) "Restore the state saved by the matching save.")
     ("get_target" "Surface" (("cr" "Context")) "The surface CR was created for.")
     ("push_group" "none" (("cr" "Context"))
      "Redirect drawing to a temporary group until pop_group.")
     ("push_group_with_content" "none" (("cr" "Context") ("content" "Content"))
      "Like push_group, with the group's content type given.")
     ("pop_group" ("Pattern" :transfer :full) (("cr" "Context"))
      "End the current group and return it as a pattern.")
     ("pop_group_to_source" "none" (("cr" "Context"))
      "End the current group and make it CR's source.")
     ("get_group_target" "Surface" (("cr" "Context")) "The surface of the current group.")
     ("set_source_rgb" "none" (("cr" "Context") ("red" "gdouble") ("green" "gdouble") ("blue" "gdouble"))
      "Set the source to an opaque color; components range from 0 to 1.")
     ("set_source_rgba" "none" (("cr" "Context") ("red" "gdouble") ("green" "gdouble")
                                ("blue" "gdouble") ("alpha" "gdouble"))
      "Set the source to a translucent color; components range from 0 to 1.")
     ("set_source" "none" (("cr" "Context") ("source" "Pattern")) "Set the source pattern.")
     ("set_source_surface" "none" (("cr" "Context") ("surface" "Surface") ("x" "gdouble") ("y" "gdouble"))
      "Use SURFACE, placed at X, Y, as the source.")
     ("get_source" "Pattern" (("cr" "Context")) "The current source pattern.")
     ("set_antialias" "none" (("cr" "Context") ("antialias" "Antialias")) "Set the antialiasing mode.")
     ("get_antialias" "Antialias" (("cr" "Context")) "The antialiasing mode.")
     ("set_dash" "none" (("cr" "Context") ("dashes" (:array "gdouble" :length 2))
                         ("num_dashes" "gint") ("offset" "gdouble"))
      "Set the dash pattern for strokes; an empty sequence disables dashing.")
     ("get_dash_count" "gint" (("cr" "Context")) "The number of entries in the dash pattern.")
     ("set_fill_rule" "none" (("cr" "Context") ("fill_rule" "FillRule")) "Set the fill rule.")
     ("get_fill_rule" "FillRule" (("cr" "Context")) "The fill rule.")
     ("set_line_cap" "none" (("cr" "Context") ("line_cap" "LineCap")) "Set how line ends are drawn.")
     ("get_line_cap" "LineCap" (("cr" "Context")) "How line ends are drawn.")
     ("set_line_join" "none" (("cr" "Context") ("line_join" "LineJoin")) "Set how line corners are drawn.")
     ("get_line_join" "LineJoin" (("cr" "Context")) "How line corners are drawn.")
     ("set_line_width" "none" (("cr" "Context") ("width" "gdouble")) "Set the stroke width.")
     ("get_line_width" "gdouble" (("cr" "Context")) "The stroke width.")
     ("set_miter_limit" "none" (("cr" "Context") ("limit" "gdouble")) "Set the miter limit.")
     ("get_miter_limit" "gdouble" (("cr" "Context")) "The miter limit.")
     ("set_operator" "none" (("cr" "Context") ("op" "Operator")) "Set the compositing operator.")
     ("get_operator" "Operator" (("cr" "Context")) "The compositing operator.")
     ("set_tolerance" "none" (("cr" "Context") ("tolerance" "gdouble"))
      "Set the curve flattening tolerance, in device units.")
     ("get_tolerance" "gdouble" (("cr" "Context")) "The curve flattening tolerance.")
     ("clip" "none" (("cr" "Context")) "Intersect the clip with the current path, then clear the path.")
     ("clip_preserve" "none" (("cr" "Context")) "Intersect the clip with the current path, keeping the path.")
     ("clip_extents" "none" (("cr" "Context") ("x1" "gdouble" :out t) ("y1" "gdouble" :out t)
                             ("x2" "gdouble" :out t) ("y2" "gdouble" :out t))
      "The clip's bounding box, as values X1 Y1 X2 Y2.")
     ("in_clip" "gboolean" (("cr" "Context") ("x" "gdouble") ("y" "gdouble"))
      "True if X, Y is inside the clip.")
     ("reset_clip" "none" (("cr" "Context")) "Remove all clipping.")
     ("fill" "none" (("cr" "Context")) "Fill the current path, then clear it.")
     ("fill_preserve" "none" (("cr" "Context")) "Fill the current path, keeping it.")
     ("fill_extents" "none" (("cr" "Context") ("x1" "gdouble" :out t) ("y1" "gdouble" :out t)
                             ("x2" "gdouble" :out t) ("y2" "gdouble" :out t))
      "The area a fill would cover, as values X1 Y1 X2 Y2.")
     ("in_fill" "gboolean" (("cr" "Context") ("x" "gdouble") ("y" "gdouble"))
      "True if X, Y would be inside a fill of the current path.")
     ("mask" "none" (("cr" "Context") ("pattern" "Pattern"))
      "Paint the source using PATTERN's alpha channel as a mask.")
     ("mask_surface" "none" (("cr" "Context") ("surface" "Surface") ("surface_x" "gdouble")
                             ("surface_y" "gdouble"))
      "Paint the source using SURFACE's alpha channel as a mask.")
     ("paint" "none" (("cr" "Context")) "Paint the source everywhere within the clip.")
     ("paint_with_alpha" "none" (("cr" "Context") ("alpha" "gdouble"))
      "Paint the source everywhere within the clip, with constant ALPHA.")
     ("stroke" "none" (("cr" "Context")) "Stroke the current path, then clear it.")
     ("stroke_preserve" "none" (("cr" "Context")) "Stroke the current path, keeping it.")
     ("stroke_extents" "none" (("cr" "Context") ("x1" "gdouble" :out t) ("y1" "gdouble" :out t)
                               ("x2" "gdouble" :out t) ("y2" "gdouble" :out t))
      "The area a stroke would cover, as values X1 Y1 X2 Y2.")
     ("in_stroke" "gboolean" (("cr" "Context") ("x" "gdouble") ("y" "gdouble"))
      "True if X, Y would be inside a stroke of the current path.")
     ("copy_page" "none" (("cr" "Context")) "Emit the current page, keeping its contents.")
     ("show_page" "none" (("cr" "Context")) "Emit and clear the current page.")))

  (add-functions
   ns "cairo_" (cairo-page "cairo-Paths.html")
   '(("new_path" "none" (("cr" "Context")) "Clear the current path.")
     ("new_sub_path" "none" (("cr" "Context")) "Start a new sub-path without a current point.")
     ("close_path" "none" (("cr" "Context")) "Close the current sub-path with a straight line.")
     ("move_to" "none" (("cr" "Context") ("x" "gdouble") ("y" "gdouble")) "Start a sub-path at X, Y.")
     ("line_to" "none" (("cr" "Context") ("x" "gdouble") ("y" "gdouble")) "Add a line to X, Y.")
     ("curve_to" "none" (("cr" "Context") ("x1" "gdouble") ("y1" "gdouble") ("x2" "gdouble")
                         ("y2" "gdouble") ("x3" "gdouble") ("y3" "gdouble"))
      "Add a cubic Bézier curve to X3, Y3 with control points X1, Y1 and X2, Y2.")
     ("arc" "none" (("cr" "Context") ("xc" "gdouble") ("yc" "gdouble") ("radius" "gdouble")
                    ("angle1" "gdouble") ("angle2" "gdouble"))
      "Add a circular arc around XC, YC, clockwise from ANGLE1 to ANGLE2 (radians).")
     ("arc_negative" "none" (("cr" "Context") ("xc" "gdouble") ("yc" "gdouble") ("radius" "gdouble")
                             ("angle1" "gdouble") ("angle2" "gdouble"))
      "Add a circular arc around XC, YC, counter-clockwise from ANGLE1 to ANGLE2.")
     ("rectangle" "none" (("cr" "Context") ("x" "gdouble") ("y" "gdouble") ("width" "gdouble")
                          ("height" "gdouble"))
      "Add a closed rectangle sub-path.")
     ("rel_move_to" "none" (("cr" "Context") ("dx" "gdouble") ("dy" "gdouble"))
      "Start a sub-path offset from the current point.")
     ("rel_line_to" "none" (("cr" "Context") ("dx" "gdouble") ("dy" "gdouble"))
      "Add a line offset from the current point.")
     ("rel_curve_to" "none" (("cr" "Context") ("dx1" "gdouble") ("dy1" "gdouble") ("dx2" "gdouble")
                             ("dy2" "gdouble") ("dx3" "gdouble") ("dy3" "gdouble"))
      "Add a Bézier curve with points relative to the current point.")
     ("text_path" "none" (("cr" "Context") ("utf8" "utf8")) "Add the outlines of UTF8's glyphs to the path.")
     ("path_extents" "none" (("cr" "Context") ("x1" "gdouble" :out t) ("y1" "gdouble" :out t)
                             ("x2" "gdouble" :out t) ("y2" "gdouble" :out t))
      "The current path's bounding box, as values X1 Y1 X2 Y2.")
     ("has_current_point" "gboolean" (("cr" "Context")) "True if the path has a current point.")
     ("get_current_point" "none" (("cr" "Context") ("x" "gdouble" :out t) ("y" "gdouble" :out t))
      "The current point, as values X Y.")))

  (add-functions
   ns "cairo_" (cairo-page "cairo-Transformations.html")
   '(("translate" "none" (("cr" "Context") ("tx" "gdouble") ("ty" "gdouble"))
      "Move the user-space origin by TX, TY.")
     ("scale" "none" (("cr" "Context") ("sx" "gdouble") ("sy" "gdouble")) "Scale user space by SX, SY.")
     ("rotate" "none" (("cr" "Context") ("angle" "gdouble")) "Rotate user space by ANGLE radians.")
     ("transform" "none" (("cr" "Context") ("matrix" "Matrix"))
      "Apply MATRIX after the current transformation.")
     ("set_matrix" "none" (("cr" "Context") ("matrix" "Matrix"))
      "Replace the current transformation with MATRIX.")
     ("get_matrix" "none" (("cr" "Context") ("matrix" "Matrix" :out t :caller-allocates t))
      "The current transformation matrix.")
     ("identity_matrix" "none" (("cr" "Context")) "Reset the transformation to the identity.")))

  (add-functions
   ns "cairo_" (cairo-page "cairo-text.html")
   '(("select_font_face" "none" (("cr" "Context") ("family" "utf8") ("slant" "FontSlant")
                                 ("weight" "FontWeight"))
      "Choose a font by family name, slant and weight (the simple \"toy\" text API).")
     ("set_font_size" "none" (("cr" "Context") ("size" "gdouble")) "Set the font size, in user units.")
     ("set_font_matrix" "none" (("cr" "Context") ("matrix" "Matrix")) "Set the font matrix.")
     ("get_font_matrix" "none" (("cr" "Context") ("matrix" "Matrix" :out t :caller-allocates t))
      "The font matrix.")
     ("set_font_options" "none" (("cr" "Context") ("options" "FontOptions")) "Set the font rendering options.")
     ("get_font_options" "none" (("cr" "Context") ("options" "FontOptions"))
      "Copy CR's font options into OPTIONS.")
     ("set_font_face" "none" (("cr" "Context") ("font_face" "FontFace" :nullable t)) "Set the font face.")
     ("get_font_face" "FontFace" (("cr" "Context")) "The current font face.")
     ("set_scaled_font" "none" (("cr" "Context") ("scaled_font" "ScaledFont")) "Set the scaled font.")
     ("get_scaled_font" "ScaledFont" (("cr" "Context")) "The current scaled font.")
     ("show_text" "none" (("cr" "Context") ("utf8" "utf8"))
      "Draw UTF8 at the current point with the current font.")
     ("text_extents" "none" (("cr" "Context") ("utf8" "utf8")
                             ("extents" "TextExtents" :out t :caller-allocates t))
      "The extents UTF8 would have if drawn with show_text.")
     ("font_extents" "none" (("cr" "Context") ("extents" "FontExtents" :out t :caller-allocates t))
      "The current font's extents.")
     ("toy_font_face_create" ("FontFace" :transfer :full) (("family" "utf8") ("slant" "FontSlant")
                                                            ("weight" "FontWeight"))
      "A font face for the toy text API.")))

  (add-functions
   ns "cairo_" (cairo-page "cairo-cairo-pattern-t.html")
   '(("pattern_create_rgb" ("Pattern" :transfer :full) (("red" "gdouble") ("green" "gdouble") ("blue" "gdouble"))
      "A pattern of one opaque color.")
     ("pattern_create_rgba" ("Pattern" :transfer :full) (("red" "gdouble") ("green" "gdouble")
                                                         ("blue" "gdouble") ("alpha" "gdouble"))
      "A pattern of one translucent color.")
     ("pattern_create_for_surface" ("Pattern" :transfer :full) (("surface" "Surface"))
      "A pattern that paints SURFACE.")
     ("pattern_create_linear" ("Pattern" :transfer :full) (("x0" "gdouble") ("y0" "gdouble")
                                                           ("x1" "gdouble") ("y1" "gdouble"))
      "A linear gradient from X0, Y0 to X1, Y1; add color stops to it.")
     ("pattern_create_radial" ("Pattern" :transfer :full) (("cx0" "gdouble") ("cy0" "gdouble") ("radius0" "gdouble")
                                                           ("cx1" "gdouble") ("cy1" "gdouble") ("radius1" "gdouble"))
      "A radial gradient between two circles; add color stops to it.")
     ("pattern_add_color_stop_rgb" "none" (("pattern" "Pattern") ("offset" "gdouble") ("red" "gdouble")
                                           ("green" "gdouble") ("blue" "gdouble"))
      "Add an opaque color stop at OFFSET (0 to 1) to a gradient.")
     ("pattern_add_color_stop_rgba" "none" (("pattern" "Pattern") ("offset" "gdouble") ("red" "gdouble")
                                            ("green" "gdouble") ("blue" "gdouble") ("alpha" "gdouble"))
      "Add a translucent color stop at OFFSET (0 to 1) to a gradient.")
     ("pattern_get_color_stop_count" "Status" (("pattern" "Pattern") ("count" "gint" :out t))
      "The number of color stops, as the second value.")
     ("pattern_set_extend" "none" (("pattern" "Pattern") ("extend" "Extend"))
      "Set what the pattern draws outside its area.")
     ("pattern_get_extend" "Extend" (("pattern" "Pattern")) "What the pattern draws outside its area.")
     ("pattern_set_filter" "none" (("pattern" "Pattern") ("filter" "Filter")) "Set the resampling filter.")
     ("pattern_get_filter" "Filter" (("pattern" "Pattern")) "The resampling filter.")
     ("pattern_set_matrix" "none" (("pattern" "Pattern") ("matrix" "Matrix")) "Set the pattern matrix.")
     ("pattern_get_matrix" "none" (("pattern" "Pattern") ("matrix" "Matrix" :out t :caller-allocates t))
      "The pattern matrix.")
     ("pattern_get_type" "PatternType" (("pattern" "Pattern")) "The kind of pattern.")
     ("pattern_status" "Status" (("pattern" "Pattern")) "The pattern's error status.")))

  (add-functions
   ns "cairo_" (cairo-page "cairo-cairo-surface-t.html")
   '(("surface_create_similar" ("Surface" :transfer :full) (("other" "Surface") ("content" "Content")
                                                            ("width" "gint") ("height" "gint"))
      "A new surface as compatible as possible with OTHER.")
     ("surface_create_similar_image" ("Surface" :transfer :full) (("other" "Surface") ("format" "Format")
                                                                  ("width" "gint") ("height" "gint"))
      "A new image surface suited to being drawn onto OTHER.")
     ("surface_finish" "none" (("surface" "Surface")) "Finish the surface; no more drawing is possible.")
     ("surface_flush" "none" (("surface" "Surface")) "Complete pending drawing before direct access.")
     ("surface_mark_dirty" "none" (("surface" "Surface")) "Tell cairo the surface was changed directly.")
     ("surface_mark_dirty_rectangle" "none" (("surface" "Surface") ("x" "gint") ("y" "gint")
                                             ("width" "gint") ("height" "gint"))
      "Tell cairo an area of the surface was changed directly.")
     ("surface_get_content" "Content" (("surface" "Surface")) "What the surface holds: color, alpha or both.")
     ("surface_get_type" "SurfaceType" (("surface" "Surface")) "The kind of surface.")
     ("surface_status" "Status" (("surface" "Surface")) "The surface's error status.")
     ("surface_set_device_offset" "none" (("surface" "Surface") ("x_offset" "gdouble") ("y_offset" "gdouble"))
      "Set an offset added to device coordinates.")
     ("surface_get_device_offset" "none" (("surface" "Surface") ("x_offset" "gdouble" :out t)
                                          ("y_offset" "gdouble" :out t))
      "The device offset, as values X Y.")
     ("surface_set_device_scale" "none" (("surface" "Surface") ("x_scale" "gdouble") ("y_scale" "gdouble"))
      "Set a scale applied to device coordinates.")
     ("surface_get_device_scale" "none" (("surface" "Surface") ("x_scale" "gdouble" :out t)
                                         ("y_scale" "gdouble" :out t))
      "The device scale, as values X Y.")))

  (add-functions
   ns "cairo_" (cairo-page "cairo-Image-Surfaces.html")
   '(("image_surface_create" ("Surface" :transfer :full) (("format" "Format") ("width" "gint") ("height" "gint"))
      "A new image surface of FORMAT, WIDTH by HEIGHT pixels, initially transparent black.")
     ("format_stride_for_width" "gint" (("format" "Format") ("width" "gint"))
      "The row stride an image of FORMAT and WIDTH needs.")
     ("image_surface_create_for_data" ("Surface" :transfer :full)
      (("data" "gpointer") ("format" "Format") ("width" "gint") ("height" "gint") ("stride" "gint"))
      "An image surface over pixel memory DATA, which must outlive the surface.")
     ("image_surface_get_data" "gpointer" (("surface" "Surface"))
      "A pointer to the surface's pixel memory; flush before reading, mark dirty after writing.")
     ("image_surface_get_format" "Format" (("surface" "Surface")) "The pixel format.")
     ("image_surface_get_width" "gint" (("surface" "Surface")) "The width in pixels.")
     ("image_surface_get_height" "gint" (("surface" "Surface")) "The height in pixels.")
     ("image_surface_get_stride" "gint" (("surface" "Surface")) "The bytes between successive rows.")))

  (add-functions
   ns "cairo_" (cairo-page "cairo-PNG-Support.html")
   '(("image_surface_create_from_png" ("Surface" :transfer :full) (("filename" "filename"))
      "A new image surface loaded from a PNG file; check its status for errors.")
     ("surface_write_to_png" "Status" (("surface" "Surface") ("filename" "filename"))
      "Write SURFACE to FILENAME as PNG.")))

  (add-functions
   ns "cairo_" (cairo-page "cairo-cairo-matrix-t.html")
   '(("matrix_init" "none" (("matrix" "Matrix" :out t :caller-allocates t) ("xx" "gdouble") ("yx" "gdouble")
                            ("xy" "gdouble") ("yy" "gdouble") ("x0" "gdouble") ("y0" "gdouble"))
      "A new matrix with the given components.")
     ("matrix_init_identity" "none" (("matrix" "Matrix" :out t :caller-allocates t))
      "A new identity matrix.")
     ("matrix_init_translate" "none" (("matrix" "Matrix" :out t :caller-allocates t)
                                      ("tx" "gdouble") ("ty" "gdouble"))
      "A new translation matrix.")
     ("matrix_init_scale" "none" (("matrix" "Matrix" :out t :caller-allocates t)
                                  ("sx" "gdouble") ("sy" "gdouble"))
      "A new scaling matrix.")
     ("matrix_init_rotate" "none" (("matrix" "Matrix" :out t :caller-allocates t) ("radians" "gdouble"))
      "A new rotation matrix.")
     ("matrix_translate" "none" (("matrix" "Matrix") ("tx" "gdouble") ("ty" "gdouble"))
      "Apply a translation to MATRIX, in place.")
     ("matrix_scale" "none" (("matrix" "Matrix") ("sx" "gdouble") ("sy" "gdouble"))
      "Apply a scale to MATRIX, in place.")
     ("matrix_rotate" "none" (("matrix" "Matrix") ("radians" "gdouble"))
      "Apply a rotation to MATRIX, in place.")
     ("matrix_invert" "Status" (("matrix" "Matrix")) "Invert MATRIX in place, if it is invertible.")
     ("matrix_multiply" "none" (("result" "Matrix" :out t :caller-allocates t) ("a" "Matrix") ("b" "Matrix"))
      "A new matrix applying A, then B.")))

  (add-functions
   ns "cairo_" (cairo-page "cairo-cairo-font-options-t.html")
   '(("font_options_create" ("FontOptions" :transfer :full) () "New font options, all defaults.")
     ("font_options_set_antialias" "none" (("options" "FontOptions") ("antialias" "Antialias"))
      "Set the antialiasing mode.")
     ("font_options_get_antialias" "Antialias" (("options" "FontOptions")) "The antialiasing mode.")
     ("font_options_set_hint_style" "none" (("options" "FontOptions") ("hint_style" "HintStyle"))
      "Set how strongly outlines are hinted.")
     ("font_options_get_hint_style" "HintStyle" (("options" "FontOptions")) "The hint style.")
     ("font_options_set_hint_metrics" "none" (("options" "FontOptions") ("hint_metrics" "HintMetrics"))
      "Set whether font metrics are rounded.")
     ("font_options_get_hint_metrics" "HintMetrics" (("options" "FontOptions")) "The hint metrics setting.")
     ("font_options_set_subpixel_order" "none" (("options" "FontOptions") ("subpixel_order" "SubpixelOrder"))
      "Set the subpixel order for subpixel antialiasing.")
     ("font_options_get_subpixel_order" "SubpixelOrder" (("options" "FontOptions")) "The subpixel order.")))

  (add-functions
   ns "cairo_" (cairo-page "cairo-Regions.html")
   '(("region_create" ("Region" :transfer :full) () "A new empty region.")
     ("region_create_rectangle" ("Region" :transfer :full) (("rectangle" "RectangleInt"))
      "A new region covering RECTANGLE.")
     ("region_num_rectangles" "gint" (("region" "Region")) "The number of rectangles in the region.")
     ("region_get_extents" "none" (("region" "Region") ("extents" "RectangleInt" :out t :caller-allocates t))
      "The region's bounding rectangle.")
     ("region_is_empty" "gboolean" (("region" "Region")) "True if the region is empty.")
     ("region_contains_point" "gboolean" (("region" "Region") ("x" "gint") ("y" "gint"))
      "True if X, Y is in the region.")
     ("region_translate" "none" (("region" "Region") ("dx" "gint") ("dy" "gint")) "Move the region.")
     ("region_union_rectangle" "Status" (("dst" "Region") ("rectangle" "RectangleInt"))
      "Add RECTANGLE to DST.")
     ("region_intersect_rectangle" "Status" (("dst" "Region") ("rectangle" "RectangleInt"))
      "Intersect DST with RECTANGLE.")
     ("region_subtract_rectangle" "Status" (("dst" "Region") ("rectangle" "RectangleInt"))
      "Remove RECTANGLE from DST.")))

  (add-functions
   ns "cairo_" (cairo-page "cairo-Error-handling.html")
   '(("status_to_string" "utf8" (("status" "Status")) "A human-readable description of STATUS.")))

  (add-functions
   ns "cairo_" (cairo-page "cairo-Version-Information.html")
   '(("version_string" "utf8" () "The version of the cairo library, as a string."))))
